<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.32">

  <title>quarto-input4a0a48e5732bca34</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-988e8b3a709629e028e858dec964560e.css">
  <link rel="stylesheet" href="styles.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-color="#000F46" class="quarto-title-block center">
  <h1 class="title"><div class="tight-title">
<div>
ECOM30004/90004
</div>
<div>
Time Series Analysis and Forecasting
</div>
<div class="spacer">

</div>
<div class="bold">
Tutorial 6
</div>
<div class="spacer">

</div>
<div class="author">
Tutor: Pengyun (Kevin) Chen
</div>
<div class="author">
University of Melbourne
</div>
<div class="author">
Semester 2, 2026
</div>
</div></h1>

<div class="quarto-title-authors">
</div>

</section>
<section id="notice" class="slide level2">
<h2>Notice</h2>
<div title="Conditions of Use">
<div class="callout callout-warning callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Conditions of Use</strong></p>
</div>
<div class="callout-content">
<ul>
<li>This document is intended for personal use and is NOT meant to be shared on the internet (e.g.&nbsp;Studocu, ThinkSwap, StudentVIP, Coursehero, etc.)</li>
<li>Do not share this document with anyone, even if they are enrolled in ECOM30004/90004.</li>
<li>Official course materials, such as lecture slides, tutorial sheets and prescribed readings should always be your primary point of reference.</li>
</ul>
</div>
</div>
</div>
</div>
<div style="height: 0.2em;">

</div>
<ul>
<li>Slides accessible here: <code>pengyunc.github.io/TSAF_Week6</code></li>
<li>Download HTML versions here: <a href="https://www.dropbox.com/scl/fo/aoxoud5ex0j42hsrod3dg/ADblAt_jJ9hpESZME9FDcWc?rlkey=0s0oyf1y3uokzvlhbzxe2yy3g&amp;st=kx2yupzr&amp;dl=0">Dropbox Link</a></li>
</ul>
</section>
<section id="bonus-opening-html-files-in-rstudio-12" class="slide level2">
<h2>(BONUS) Opening HTML Files in RStudio (1/2)</h2>
<p>It is possible to open HTML files in the <strong>Viewer</strong> pane of RStudio <grey>(bottom right panel)</grey>: <myimage src="figures/figure1.png" width="90%"></myimage></p>
</section>
<section id="bonus-opening-html-files-in-rstudio-22" class="slide level2">
<h2>(BONUS) Opening HTML Files in RStudio (2/2)</h2>
<p><blue>Step 1: </blue>Set up your working directory containing HTML files:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="fu">setwd</span>(<span class="st">"Your working directory goes here"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div style="height: 0.5em;">

</div>
<p><blue>Step 2: </blue>Define the following function once:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a></a><span class="co"># Copy everything below into the console window and run it:</span></span>
<span id="cb2-2"><a></a>openfile <span class="ot">&lt;-</span> <span class="cf">function</span>(src) {</span>
<span id="cb2-3"><a></a>  tmp_dir <span class="ot">&lt;-</span> <span class="fu">tempfile</span>()</span>
<span id="cb2-4"><a></a>  <span class="fu">dir.create</span>(tmp_dir)</span>
<span id="cb2-5"><a></a>  tmp_html <span class="ot">&lt;-</span> <span class="fu">file.path</span>(tmp_dir, <span class="fu">basename</span>(src))</span>
<span id="cb2-6"><a></a>  <span class="fu">file.copy</span>(src, tmp_html, <span class="at">overwrite =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-7"><a></a>  rstudioapi<span class="sc">::</span><span class="fu">viewer</span>(tmp_html)</span>
<span id="cb2-8"><a></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div style="height: 0.5em;">

</div>
<p><blue>Step 3: </blue>Call this function with file name as character string:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="co"># Just a few examples here:</span></span>
<span id="cb3-2"><a></a><span class="fu">openfile</span>(<span class="st">"Lecture5.html"</span>)</span>
<span id="cb3-3"><a></a><span class="fu">openfile</span>(<span class="st">"Tutorial6.html"</span>)</span>
<span id="cb3-4"><a></a><span class="fu">openfile</span>(<span class="st">"ECOM30004_Tutorial_6_Slides.html"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="this-tutorial" class="slide level2">
<h2>This tutorial</h2>
<p><blue>In this tutorial, we demonstrate forecasting the 2020Q1 CPI level, including stationarity tests, ARIMA model selection, and the final forecast computation.</blue></p>
<div style="height: 0.2em;">

</div>
<div title="Agenda">
<div class="callout callout-note callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Agenda</strong></p>
</div>
<div class="callout-content">
<ul>
<li><p><blue>Exercise 1(a):</blue> Transform CPI levels into log differences and select the ADF specification.</p></li>
<li><p><blue>Exercise 1(b):</blue> Test the log-differenced CPI for a unit root (ADF).</p></li>
<li><p><blue>Exercise 1(c):</blue> Select the ARIMA model using AICc and Ljung–Box diagnostics.</p></li>
<li><p><blue>Exercise 1(d):</blue> Does the choice of using observation indices or observation dates matter?</p></li>
<li><p><blue>Exercise 1(e):</blue> Forecast inflation and CPI for 2020Q1.</p></li>
<li><p><blue>Exercise 2:</blue> Rearranging a time series model into its corresponding ADF test equation.</p></li>
</ul>
</div>
</div>
</div>
</div>
<div style="height: 0.2em;">

</div>
</section>
<section id="we-know-that-taking-the-logs-is-not-enough" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">We know that taking the logs is not enough…</h2>
<p>Recall the unit root test results for log <code>CPI</code> from Self-directed Activities 5.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a></a>dt <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"CPI.csv"</span>)</span>
<span id="cb4-2"><a></a>Y <span class="ot">&lt;-</span> <span class="fu">ts</span>(<span class="fu">log</span>(dt<span class="sc">$</span>CPI), <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">1922</span>,<span class="dv">2</span>), <span class="at">end =</span> <span class="fu">c</span>(<span class="dv">2025</span>,<span class="dv">2</span>), <span class="at">frequency=</span><span class="dv">4</span>)</span>
<span id="cb4-3"><a></a>Y <span class="ot">&lt;-</span> <span class="fu">window</span>(Y, <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">1946</span>,<span class="dv">1</span>), <span class="at">end =</span> <span class="fu">c</span>(<span class="dv">2019</span>,<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="horizontal-line">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a><span class="fu">plot</span>(Y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="ECOM30004_Tutorial_6_files/figure-revealjs/unnamed-chunk-5-1.png" width="960" class="r-stretch"><p>An upward trend is obvious <blue><span class="math inline">\(\to\)</span> add a time trend in deterministic specification<blue></blue></blue></p>
</section>
<section id="we-know-that-taking-the-logs-is-not-enough-1" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">We know that taking the logs is not enough…</h2>
<div class="callout-question">
<p>Carry out an ADF test of <code>Y</code>, present (i) the estimated test equation, (ii) the <span class="math inline">\(t_{\text{ADF}}\)</span> test statistic, 5% critical value and decision, and (iii) its <span class="math inline">\(p\)</span>-value.</p>
</div>
<div style="height: 0.5em;">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a><span class="fu">library</span>(urca)    <span class="co"># For use of ur.df function</span></span>
<span id="cb6-2"><a></a>adf <span class="ot">&lt;-</span> <span class="fu">ur.df</span>(Y, <span class="at">type =</span> <span class="st">"trend"</span>, <span class="at">selectlags =</span> <span class="st">"AIC"</span>)</span>
<span id="cb6-3"><a></a>p_adf <span class="ot">&lt;-</span> <span class="fu">punitroot</span>(adf<span class="sc">@</span>teststat[<span class="dv">1</span>], <span class="at">trend =</span> <span class="st">"ct"</span>, <span class="at">statistic =</span> <span class="st">"t"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div style="height: 0.5em;">

</div>
<div class="panel-tabset">
<ul id="tabset-1" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-1-1">(i) test equation</a></li><li><a href="#tabset-1-2">(ii) test summary</a></li><li><a href="#tabset-1-3">(iii) <span class="math inline">\(p\)</span>-value</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1">
<p>The test equation is: <span class="math display">\[\Delta Y_{t}=\beta_{0}+\beta_{1}t+\varphi Y_{t-1}+\sum^{p-1}_{k=1}\psi_{k} \Delta Y_{t-k}+U_{t}\]</span> The hypotheses are: <span class="math display">\[\begin{align}
H_{0}:&amp;\;\varphi=0&amp; &amp;\textsf{($Y_{t}$ has a unit root)}\\
H_{1}:&amp;\;\varphi&lt;0&amp; &amp;\textsf{($Y_{t}$ does not have a unit root)}
\end{align}\]</span> The number of lags of <span class="math inline">\(\Delta Y_{t}\)</span> (i.e., <span class="math inline">\(p-1\)</span>) is selected by an information criterion (AIC), where <span class="math inline">\(p\)</span> is the order of the underlying AR model.</p>
</div>
<div id="tabset-1-2">
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a><span class="fu">summary</span>(adf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression trend 


Call:
lm(formula = z.diff ~ z.lag.1 + 1 + tt + z.diff.lag)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.031901 -0.005565 -0.000645  0.004216  0.045287 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  8.657e-03  3.805e-03   2.275   0.0236 *  
z.lag.1      2.743e-04  2.772e-03   0.099   0.9212    
tt          -2.428e-05  3.733e-05  -0.651   0.5159    
z.diff.lag   5.147e-01  5.049e-02  10.193   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.01025 on 290 degrees of freedom
Multiple R-squared:  0.3263,    Adjusted R-squared:  0.3193 
F-statistic: 46.82 on 3 and 290 DF,  p-value: &lt; 2.2e-16


Value of test-statistic is: 0.099 16.8276 3.9857 

Critical values for test statistics: 
      1pct  5pct 10pct
tau3 -3.98 -3.42 -3.13
phi2  6.15  4.71  4.05
phi3  8.34  6.30  5.36</code></pre>
</div>
</div>
</div>
<div id="tabset-1-3">
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a></a><span class="fu">print</span>(p_adf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9973104</code></pre>
</div>
</div>
<div style="height: 0.5em;">

</div>
Since <span class="math inline">\(p=0.997&gt;0.05\)</span>, we <teal><strong>fail to reject</strong> the null hypothesis <span class="math inline">\(H_{0}\)</span>: there is unit root</teal>.
<div style="height: 0.5em;">

</div>
<p><blue><span class="math inline">\(\implies\)</span> Simply removing the trend component is not enough to make <span class="math inline">\(Y_{t}\)</span> stationary. </blue></p>
<p><blue><span class="math inline">\(\implies\)</span> We need to take the first difference of log <code>CPI</code>.</blue></p>
</div>
</div>
</div>
</section>
<section id="exercise-1a" class="slide level2">
<h2>Exercise 1(a)</h2>
<div class="callout-question">
<p>Next create the first difference time series <span class="math inline">\(\Delta Y_{t}\)</span> and a time series plot. Decide whether a trend is required for a unit root test for <span class="math inline">\(\Delta Y_{t}\)</span>.</p>
</div>
<div style="height: 0.5em;">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a>DY <span class="ot">&lt;-</span> <span class="fu">diff</span>(Y)   <span class="co"># DY is the log difference of the CPI -&gt; Inflation</span></span>
<span id="cb11-2"><a></a><span class="fu">plot</span>(DY)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="ECOM30004_Tutorial_6_files/figure-revealjs/unnamed-chunk-9-1.png" width="960" class="r-stretch"><p><blue><strong>Observation:</strong> There is no evidence of a linear trend in this time series.</blue> There are some extended periods (e.g.&nbsp;early 1950’s and 1970-80’s) when inflation was higher.</p>
</section>
<section id="exercise-1b" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Exercise 1(b)</h2>
<div class="callout-question">
<p>Carry out the unit root test on <span class="math inline">\(\Delta Y_{t}\)</span>. Conclude how many differences are required for log CPI to be stationary.</p>
</div>
<div style="height: 0.5em;">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy" data-id="quarto-animate-code"><code class="sourceCode r hljs"><span id="cb12-1" class="hljs-ln-code"><a></a>adf <span class="ot">&lt;-</span> <span class="fu">ur.df</span>(DY, <span class="at">type =</span> <span class="st">"drift"</span>, <span class="at">selectlags =</span> <span class="st">"AIC"</span>)</span>
<span id="cb12-2" class="hljs-ln-code"><a></a>p_adf <span class="ot">&lt;-</span> <span class="fu">punitroot</span>(adf<span class="sc">@</span>teststat[<span class="dv">1</span>], <span class="at">trend =</span> <span class="st">"c"</span>, <span class="at">statistic =</span> <span class="st">"t"</span>)</span>
<span id="cb12-3" class="hljs-ln-code"><a></a><span class="fu">summary</span>(adf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression drift 


Call:
lm(formula = z.diff ~ z.lag.1 + 1 + z.diff.lag)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.030300 -0.004863 -0.000533  0.003937  0.039013 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.0031901  0.0008224   3.879  0.00013 ***
z.lag.1     -0.2581651  0.0501006  -5.153 4.75e-07 ***
z.diff.lag  -0.4253700  0.0530437  -8.019 2.64e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.009393 on 290 degrees of freedom
Multiple R-squared:  0.3652,    Adjusted R-squared:  0.3608 
F-statistic: 83.41 on 2 and 290 DF,  p-value: &lt; 2.2e-16


Value of test-statistic is: -5.1529 13.2782 

Critical values for test statistics: 
      1pct  5pct 10pct
tau2 -3.44 -2.87 -2.57
phi1  6.47  4.61  3.79</code></pre>
</div>
</div>
<div class="horizontal-line">

</div>
<p>The estimated ADF test equation is:</p>
<p><span class="math display">\[\widehat{\Delta(\Delta Y_{t})}=0.0031-0.258\Delta Y_{t-1}-0.4253\Delta(\Delta Y_{t-1})\]</span></p>
</section>
<section id="exercise-1b-1" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Exercise 1(b)</h2>
<div class="callout-question">
<p>Carry out the unit root test on <span class="math inline">\(\Delta Y_{t}\)</span>. Conclude how many differences are required for log CPI to be stationary.</p>
</div>
<div style="height: 0.5em;">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy" data-id="quarto-animate-code"><code class="sourceCode r hljs"><span id="cb14-1" class="hljs-ln-code"><a></a>adf <span class="ot">&lt;-</span> <span class="fu">ur.df</span>(DY, <span class="at">type =</span> <span class="st">"drift"</span>, <span class="at">selectlags =</span> <span class="st">"AIC"</span>)</span>
<span id="cb14-2" class="hljs-ln-code"><a></a>p_adf <span class="ot">&lt;-</span> <span class="fu">punitroot</span>(adf<span class="sc">@</span>teststat[<span class="dv">1</span>], <span class="at">trend =</span> <span class="st">"c"</span>, <span class="at">statistic =</span> <span class="st">"t"</span>)</span>
<span id="cb14-3" class="hljs-ln-code"><a></a><span class="fu">summary</span>(adf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression drift 


Call:
lm(formula = z.diff ~ z.lag.1 + 1 + z.diff.lag)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.030300 -0.004863 -0.000533  0.003937  0.039013 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.0031901  0.0008224   3.879  0.00013 ***
z.lag.1     -0.2581651  0.0501006  -5.153 4.75e-07 ***
z.diff.lag  -0.4253700  0.0530437  -8.019 2.64e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.009393 on 290 degrees of freedom
Multiple R-squared:  0.3652,    Adjusted R-squared:  0.3608 
F-statistic: 83.41 on 2 and 290 DF,  p-value: &lt; 2.2e-16


Value of test-statistic is: -5.1529 13.2782 

Critical values for test statistics: 
      1pct  5pct 10pct
tau2 -3.44 -2.87 -2.57
phi1  6.47  4.61  3.79</code></pre>
</div>
</div>
<div class="horizontal-line">

</div>
<p>The <span class="math inline">\(t\)</span>-statistic is <span class="math inline">\(-5.1529\)</span>, and the <span class="math inline">\(5\%\)</span> critical value is <span class="math inline">\(-2.87\)</span>.</p>
<p><blue>Since <span class="math inline">\(-5.1539&lt;-2.87\)</span>, we <strong>reject</strong> <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\Delta Y_{t}\)</span> has a unit root.</blue></p>
</section>
<section id="exercise-1b-2" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Exercise 1(b)</h2>
<div class="callout-question">
<p>Carry out the unit root test on <span class="math inline">\(\Delta Y_{t}\)</span>. Conclude how many differences are required for log CPI to be stationary.</p>
</div>
<div style="height: 0.5em;">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a></a>adf <span class="ot">&lt;-</span> <span class="fu">ur.df</span>(DY, <span class="at">type =</span> <span class="st">"drift"</span>, <span class="at">selectlags =</span> <span class="st">"AIC"</span>)</span>
<span id="cb16-2"><a></a>p_adf <span class="ot">&lt;-</span> <span class="fu">punitroot</span>(adf<span class="sc">@</span>teststat[<span class="dv">1</span>], <span class="at">trend =</span> <span class="st">"c"</span>, <span class="at">statistic =</span> <span class="st">"t"</span>)</span>
<span id="cb16-3"><a></a><span class="fu">summary</span>(adf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div style="height: 0.5em;">

</div>
<p>The <span class="math inline">\(t\)</span>-statistic is <span class="math inline">\(-5.1529\)</span>, and the <span class="math inline">\(5\%\)</span> critical value is <span class="math inline">\(-2.87\)</span>.</p>
<p>Since <span class="math inline">\(-5.1539&lt;-2.87\)</span>, we <strong>reject</strong> <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\Delta Y_{t}\)</span> has a unit root.</p>
<div class="fragment">
<div class="horizontal-line">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a><span class="fu">print</span>(p_adf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9.828593e-06</code></pre>
</div>
</div>
<div style="height: 0.5em;">

</div>
<p><teal>Alternatively, since <span class="math inline">\(p=9.82\times 10^{-6}&lt;0.05\)</span>, we <strong>reject <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\Delta Y_{t}\)</span> has a unit root</strong>.</teal></p>
</div>
<div class="fragment">
<div class="horizontal-line">

</div>
<p><blue><strong>Conclusion:</strong> To render log CPI stationary, it is necessary to difference the series <em>once</em>.</blue></p>
</div>
</section>
<section id="exercise-1c" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Exercise 1(c)</h2>
<div class="callout-question">
<p>Specify and estimate an appropriate ARIMA(<span class="math inline">\(p,d,q\)</span>) model for <span class="math inline">\(Y_{t}\)</span>.</p>
</div>
<div style="height: 0.5em;">

</div>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<ul>
<li>Since first differencing is required for log CPI to be stationary, we need <span class="math inline">\(d=1\)</span>.</li>
<li>How to select <span class="math inline">\((p,q)\)</span>? <green><span class="math inline">\(\to\)</span> Conduct a grid search for <span class="math inline">\(p=0,\dots,4\)</span> and <span class="math inline">\(q=0,\dots,4\)</span></green></li>
</ul>
</div>
</div>
</div>
<div class="horizontal-line">

</div>
<div title="Code Structure">
<div class="callout callout-note callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Code Structure</strong></p>
</div>
<div class="callout-content">
<ul>
<li><p>Set up container matrices for AICc values (<code>AICc</code>) and Ljung-Box test <span class="math inline">\(p\)</span>-values (<code>LBp</code>)</p></li>
<li><p>For each <span class="math inline">\((p,q)\)</span> combination:</p>
<ul>
<li><p>Fit the ARIMA(<span class="math inline">\(p,1,q\)</span>) model with <code>Arima()</code> function, and extract AICc</p></li>
<li><p>Extract the Ljung-Box <span class="math inline">\(p\)</span>-values with <code>Box.test()</code> function</p></li>
</ul></li>
<li><p>Choose the model with the <strong>lowest</strong> AICc, and verify that its <teal>Ljung-Box <span class="math inline">\(H_{0}\)</span> (no autocorrelation)</teal> is not rejected.</p></li>
</ul>
</div>
</div>
</div>
</div>
</section>
<section id="exercise-1c-1" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Exercise 1(c)</h2>
<div class="callout-question">
<p>Specify and estimate an appropriate ARIMA(<span class="math inline">\(p,d,q\)</span>) model for <span class="math inline">\(Y_{t}\)</span>.</p>
</div>
<div style="height: 0.5em;">

</div>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<ul>
<li>Since first differencing is required for log CPI to be stationary, we need <span class="math inline">\(d=1\)</span>.</li>
<li>How to select <span class="math inline">\((p,q)\)</span>? <green><span class="math inline">\(\to\)</span> Conduct a grid search for <span class="math inline">\(p=0,\dots,4\)</span> and <span class="math inline">\(q=0,\dots,4\)</span></green></li>
</ul>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy" data-id="quarto-animate-code"><code class="sourceCode r hljs"><span id="cb19-1" class="hljs-ln-code"><a></a><span class="fu">library</span>(forecast)</span>
<span id="cb19-2" class="hljs-ln-code"><a></a></span>
<span id="cb19-3" class="hljs-ln-code"><a></a>pmax <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb19-4" class="hljs-ln-code"><a></a>qmax <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb19-5" class="hljs-ln-code"><a></a></span>
<span id="cb19-6" class="hljs-ln-code"><a></a>LBp <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="at">nrow=</span>pmax<span class="sc">+</span><span class="dv">1</span>, <span class="at">ncol=</span>qmax<span class="sc">+</span><span class="dv">1</span>)</span>
<span id="cb19-7" class="hljs-ln-code"><a></a><span class="fu">rownames</span>(LBp) <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">"p="</span>, <span class="dv">0</span><span class="sc">:</span>pmax)</span>
<span id="cb19-8" class="hljs-ln-code"><a></a><span class="fu">colnames</span>(LBp) <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">"q="</span>, <span class="dv">0</span><span class="sc">:</span>qmax)</span>
<span id="cb19-9" class="hljs-ln-code"><a></a>AICc <span class="ot">&lt;-</span> LBp</span>
<span id="cb19-10" class="hljs-ln-code"><a></a></span>
<span id="cb19-11" class="hljs-ln-code"><a></a><span class="cf">for</span> (p <span class="cf">in</span> <span class="dv">0</span><span class="sc">:</span>pmax){</span>
<span id="cb19-12" class="hljs-ln-code"><a></a>  <span class="cf">for</span> (q <span class="cf">in</span> <span class="dv">0</span><span class="sc">:</span>qmax){</span>
<span id="cb19-13" class="hljs-ln-code"><a></a>    eq <span class="ot">&lt;-</span> <span class="fu">Arima</span>(DY, <span class="at">order=</span><span class="fu">c</span>(p,<span class="dv">0</span>,q))</span>
<span id="cb19-14" class="hljs-ln-code"><a></a>    LBp[p<span class="sc">+</span><span class="dv">1</span>,q<span class="sc">+</span><span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">Box.test</span>(eq<span class="sc">$</span>residuals, <span class="at">lag =</span> <span class="dv">8</span>, </span>
<span id="cb19-15" class="hljs-ln-code"><a></a>                             <span class="at">type =</span> <span class="st">"Ljung-Box"</span>, <span class="at">fitdf =</span> p<span class="sc">+</span>q)<span class="sc">$</span>p.value</span>
<span id="cb19-16" class="hljs-ln-code"><a></a>    AICc[p<span class="sc">+</span><span class="dv">1</span>,q<span class="sc">+</span><span class="dv">1</span>] <span class="ot">&lt;-</span> eq<span class="sc">$</span>aicc</span>
<span id="cb19-17" class="hljs-ln-code"><a></a>  }  </span>
<span id="cb19-18" class="hljs-ln-code"><a></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exercise-1c-2" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Exercise 1(c)</h2>
<div class="callout-question">
<p>Specify and estimate an appropriate ARIMA(<span class="math inline">\(p,d,q\)</span>) model for <span class="math inline">\(Y_{t}\)</span>.</p>
</div>
<div style="height: 0.5em;">

</div>
<p>Residual autocorrelation result (<code>TRUE</code> if <span class="math inline">\(H_{0}\)</span> maintained)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a></a><span class="fu">print</span>(LBp<span class="sc">&lt;</span><span class="fl">0.05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     q=0  q=1   q=2   q=3   q=4
p=0 TRUE TRUE  TRUE  TRUE  TRUE
p=1 TRUE TRUE FALSE FALSE FALSE
p=2 TRUE TRUE FALSE FALSE FALSE
p=3 TRUE TRUE FALSE FALSE FALSE
p=4 TRUE TRUE  TRUE FALSE  TRUE</code></pre>
</div>
</div>
<div style="height: 0.5em;">

</div>
<p>Model to minimise AICc:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a></a><span class="fu">print</span>(AICc<span class="sc">==</span><span class="fu">min</span>(AICc))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      q=0   q=1   q=2   q=3   q=4
p=0 FALSE FALSE FALSE FALSE FALSE
p=1 FALSE FALSE FALSE  TRUE FALSE
p=2 FALSE FALSE FALSE FALSE FALSE
p=3 FALSE FALSE FALSE FALSE FALSE
p=4 FALSE FALSE FALSE FALSE FALSE</code></pre>
</div>
</div>
<div style="height: 0.5em;">

</div>
<div class="fragment">
<p><blue><strong>Conclusion:</strong> The chosen model is ARMA(<span class="math inline">\(1,3\)</span>) for <span class="math inline">\(\Delta Y_{t}\)</span>, equivalently ARIMA(<span class="math inline">\(1,1,3\)</span>) for <span class="math inline">\(Y_{t}\)</span>.</blue></p>
</div>
</section>
<section id="exercise-1c-3" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Exercise 1(c)</h2>
<div class="callout-question">
<p><blue>Model the linear trend using the observation indices <span class="math inline">\(t=1,2,\dots,n\)</span>. </blue></p>
<p>Combining a difference and a linear trend in the model requires some careful interpretation - write out the model in equation form and interpret the coefficients.</p>
</div>
<div style="height: 0.5em;">

</div>
<div class="panel-tabset">
<ul id="tabset-2" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-2-1">ARIMA(1,0,3) on <span class="math inline">\(\Delta Y_{t}\)</span></a></li><li><a href="#tabset-2-2">ARIMA(1,1,3) on <span class="math inline">\(Y_{t}\)</span></a></li><li><a href="#tabset-2-3">Comments on Forecasting</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1">
<p>To estimate the ARIMA(1,0,3) model for <span class="math inline">\(\Delta Y_{t}\)</span>, with that difference already taken in computing <code>DY</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a></a>eq_a <span class="ot">&lt;-</span> <span class="fu">Arima</span>(DY, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">3</span>))</span>
<span id="cb24-2"><a></a><span class="fu">print</span>(<span class="fu">round</span>(eq_a<span class="sc">$</span>coef,<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      ar1       ma1       ma2       ma3 intercept 
   0.8316   -0.6377    0.2380    0.1276    0.0120 </code></pre>
</div>
</div>
<div class="horizontal-line">

</div>
<p>In equation form, this estimated model can be written as:</p>
<p><span class="math display">\[\begin{align}
\Delta Y_{t}&amp;=0.0120 +\widehat{\Delta Z}_{t}\\
\widehat{\Delta Z}_{t}&amp;=0.8316\widehat{\Delta Z}_{t-1}+\widehat{U}_{t}-0.6377\widehat{U}_{t-1}+0.2380\widehat{U}_{t-2}+0.1276\widehat{U}_{t-3}
\end{align}\]</span></p>
<p>The intercept of the model, <span class="math inline">\(\widehat{\beta}_{1}=0.0120\)</span>, implies the estimated mean rate of inflation is <span class="math inline">\(0.0120\)</span>, or <span class="math inline">\(1.2\%\)</span> per quarter (this is a quarterly time series).</p>
</div>
<div id="tabset-2-2">
<p>The same model may be estimated as an ARIMA(<span class="math inline">\(1,1,3\)</span>) model for <span class="math inline">\(Y_{t}\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a></a>eq_b <span class="ot">&lt;-</span> <span class="fu">Arima</span>(Y, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">3</span>), <span class="at">include.drift =</span> <span class="cn">TRUE</span>)</span>
<span id="cb26-2"><a></a><span class="fu">print</span>(<span class="fu">round</span>(eq_b<span class="sc">$</span>coef,<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    ar1     ma1     ma2     ma3   drift 
 0.8316 -0.6377  0.2380  0.1276  0.0120 </code></pre>
</div>
</div>
<div class="horizontal-line">

</div>
<p><span class="math display">\[\begin{align}
Y_{t}&amp;=0.0120t +\widehat{Z}_{t}\\
\widehat{\Delta Z}_{t}&amp;=0.8316\widehat{\Delta Z}_{t-1}+\widehat{U}_{t}-0.6377\widehat{U}_{t-1}+0.2380\widehat{U}_{t-2}+0.1276\widehat{U}_{t-3}
\end{align}\]</span></p>
<div title="Note">
<div class="callout callout-note callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<ul>
<li><code>include.drift = TRUE</code> option is necessary for the inclusion of <span class="math inline">\(\beta_{1}\)</span> when the differencing is specified under <code>order = c(1,1,3)</code> rather than taking the difference beforehand and included in the model as <code>DY</code>.</li>
<li>It is called “drift” because a constant in a first-differenced process corresponds to a linear trend in the level of <span class="math inline">\(Y_{t}\)</span>.</li>
<li>Alternatively, replicating this with <code>xreg</code> argument:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a></a>t <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(Y)</span>
<span id="cb28-2"><a></a>eq_b_xreg <span class="ot">&lt;-</span> <span class="fu">Arima</span>(Y, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">3</span>), <span class="at">xreg =</span> t)</span>
<span id="cb28-3"><a></a><span class="fu">print</span>(<span class="fu">round</span>(eq_b_xreg<span class="sc">$</span>coef,<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    ar1     ma1     ma2     ma3    xreg 
 0.8316 -0.6377  0.2380  0.1276  0.0120 </code></pre>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div id="tabset-2-3">
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a></a><span class="fu">print</span>(<span class="fu">round</span>(eq_a<span class="sc">$</span>coef,<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      ar1       ma1       ma2       ma3 intercept 
   0.8316   -0.6377    0.2380    0.1276    0.0120 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a></a><span class="fu">print</span>(<span class="fu">round</span>(eq_b<span class="sc">$</span>coef,<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    ar1     ma1     ma2     ma3   drift 
 0.8316 -0.6377  0.2380  0.1276  0.0120 </code></pre>
</div>
</div>
<div class="horizontal-line">

</div>
<ul>
<li>The two approaches are equivalent for estimation, as can be seen from these coefficient estimates. There is a difference, however, between the two when it comes to forecasting.
<ul>
<li>The ARMA(1,3) model on <span class="math inline">\(\Delta Y_{t}\)</span> (<code>DY</code>) will generate forecasts for <span class="math inline">\(\Delta Y_{t}\)</span> (inflation), while the second is model for <span class="math inline">\(Y_{t}\)</span> (<code>Y</code>, log CPI). <blue><span class="math inline">\(\to\)</span> We will demonstrate this in part (e).</blue></li>
</ul></li>
<li>Neither is necessarily better/worse, it just depends on the intended purpose.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="exercise-1d" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Exercise 1(d)</h2>
<div class="callout-question">
<p>In previous applications we have modeled the linear trend using the observation <em>dates</em> <span class="math inline">\(\text{Time}_{t}\)</span>. Set up the same ARIMA<span class="math inline">\((p,d,q)\)</span> model for <span class="math inline">\(Y_{t}\)</span> as (c), but use the observation dates instead.</p>
<p><blue>Show how this is equivalent to using observation indices for the trend.</blue></p>
</div>
<div style="height: 0.5em;">

</div>
<p><blue>What are <strong>observation dates</strong> and <strong>observation indices</strong>?</blue></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a></a>t <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(Y)   <span class="co"># Observation Indices</span></span>
<span id="cb34-2"><a></a>Time <span class="ot">&lt;-</span> <span class="fu">time</span>(Y)    <span class="co"># Observation Dates</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div style="height: 0.5em;">

</div>
<p>Here are the first and last few observation indices and dates:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">t =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(Y), <span class="at">Time =</span> <span class="fu">time</span>(Y))</span>
<span id="cb35-2"><a></a>yr <span class="ot">&lt;-</span> <span class="fu">floor</span>(df<span class="sc">$</span>Time)</span>
<span id="cb35-3"><a></a>qtr <span class="ot">&lt;-</span> <span class="fu">round</span>((df<span class="sc">$</span>Time <span class="sc">-</span> yr) <span class="sc">*</span> <span class="dv">4</span>) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb35-4"><a></a><span class="fu">rownames</span>(df) <span class="ot">&lt;-</span> <span class="fu">paste</span>(yr, <span class="fu">paste0</span>(<span class="st">"Q"</span>, qtr))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div style="height: 0.5em;">

</div>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        t    Time
1946 Q1 1 1946.00
1946 Q2 2 1946.25
1946 Q3 3 1946.50
1946 Q4 4 1946.75
1947 Q1 5 1947.00
1947 Q2 6 1947.25</code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a></a><span class="fu">tail</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          t    Time
2018 Q3 291 2018.50
2018 Q4 292 2018.75
2019 Q1 293 2019.00
2019 Q2 294 2019.25
2019 Q3 295 2019.50
2019 Q4 296 2019.75</code></pre>
</div>
</div>
</div></div>
</section>
<section id="exercise-1d-1" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Exercise 1(d)</h2>
<div class="callout-question">
<p>In previous applications we have modeled the linear trend using the observation <em>dates</em> <span class="math inline">\(\text{Time}_{t}\)</span>. Set up the same ARIMA<span class="math inline">\((p,d,q)\)</span> model for <span class="math inline">\(Y_{t}\)</span> as (c), but use the observation dates instead.</p>
<p><blue>Show how this is equivalent to using observation indices for the trend.</blue></p>
</div>
<div style="height: 0.5em;">

</div>
<p>We start from the trend model with observation <em>indices</em> (<span class="math inline">\(t\)</span>): <span class="math display">\[\begin{align}
Y_{t}&amp;=\mathbb{E}(Y_{t})+Z_{t}\\
\textsf{where}\quad \mathbb{E}(Y_{t})&amp;=\beta_{0}+\textcolor{black}{\beta_{1}}t &amp; &amp;\textsf{(Trend model with observation indices)}\\
\mathbb{E}(Y_{t})&amp;=\beta^{*}_{0}+\beta^{*}_{1}\text{Time}_{t} &amp; &amp;\textsf{(Trend model with observation dates)}
\end{align}\]</span></p>
</section>
<section id="exercise-1d-2" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Exercise 1(d)</h2>
<div class="callout-question">
<p>In previous applications we have modeled the linear trend using the observation <em>dates</em> <span class="math inline">\(\text{Time}_{t}\)</span>. Set up the same ARIMA<span class="math inline">\((p,d,q)\)</span> model for <span class="math inline">\(Y_{t}\)</span> as (c), but use the observation dates instead.</p>
<p><blue>Show how this is equivalent to using observation indices for the trend.</blue></p>
</div>
<div style="height: 0.5em;">

</div>
<p>We start from the trend model with observation <em>indices</em> (<span class="math inline">\(t\)</span>): <span class="math display">\[\begin{align}
Y_{t}&amp;=\mathbb{E}(Y_{t})+Z_{t}\\
\textsf{where}\quad \mathbb{E}(Y_{t})&amp;=\beta_{0}+\textcolor{purple}{\beta_{1}}t &amp; &amp;\textsf{(Trend model with observation indices)}\\
\mathbb{E}(Y_{t})&amp;=\beta^{*}_{0}+\beta^{*}_{1}\text{Time}_{t} &amp; &amp;\textsf{(Trend model with observation dates)}
\end{align}\]</span></p>
<p><purple>The interpretation of <span class="math inline">\(\beta_{1}\)</span> is the change in mean of <span class="math inline">\(Y_{t}\)</span> when <span class="math inline">\(t\)</span> increases by one (i.e.&nbsp;when time advances by one period, one <em>quarter</em> in this case.)</purple></p>
</section>
<section id="exercise-1d-3" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Exercise 1(d)</h2>
<div class="callout-question">
<p>In previous applications we have modeled the linear trend using the observation <em>dates</em> <span class="math inline">\(\text{Time}_{t}\)</span>. Set up the same ARIMA<span class="math inline">\((p,d,q)\)</span> model for <span class="math inline">\(Y_{t}\)</span> as (c), but use the observation dates instead.</p>
<p><blue>Show how this is equivalent to using observation indices for the trend.</blue></p>
</div>
<div style="height: 0.5em;">

</div>
<p>We start from the trend model with observation <em>indices</em> (<span class="math inline">\(t\)</span>): <span class="math display">\[\begin{align}
Y_{t}&amp;=\mathbb{E}(Y_{t})+Z_{t}\\
\textsf{where}\quad \mathbb{E}(Y_{t})&amp;=\beta_{0}+\textcolor{purple}{\beta_{1}}t &amp; &amp;\textsf{(Trend model with observation indices)}\\
\mathbb{E}(Y_{t})&amp;=\beta^{*}_{0}+\textcolor{teal}{\beta^{*}_{1}}\text{Time}_{t} &amp; &amp;\textsf{(Trend model with observation dates)}
\end{align}\]</span></p>
<p><purple>The interpretation of <span class="math inline">\(\beta_{1}\)</span> is the change in mean of <span class="math inline">\(Y_{t}\)</span> when <span class="math inline">\(t\)</span> increases by one (i.e.&nbsp;when time advances by one period, one <em>quarter</em> in this case.)</purple></p>
<div style="height: 0.2em;">

</div>
<p><teal>The interpretation of <span class="math inline">\(\beta^{*}_{1}\)</span> is the change in mean of <span class="math inline">\(Y_{t}\)</span> when <span class="math inline">\(\text{Time}_{t}\)</span> increases by one (i.e.&nbsp;one <em>year</em> in this case.)</teal></p>
<div style="height: 0.2em;">

</div>
<div class="fragment">
<p><blue><strong>Question:</strong> </blue>How are <span class="math inline">\(\textcolor{purple}{\beta_{1}}\)</span> and <span class="math inline">\(\textcolor{teal}{\beta^{*}_{1}}\)</span> related?</p>
</div>
</section>
<section id="exercise-1d-4" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Exercise 1(d)</h2>
<div class="callout-question">
<p>In previous applications we have modeled the linear trend using the observation <em>dates</em> <span class="math inline">\(\text{Time}_{t}\)</span>. Set up the same ARIMA<span class="math inline">\((p,d,q)\)</span> model for <span class="math inline">\(Y_{t}\)</span> as (c), but use the observation dates instead.</p>
<p><blue>Show how this is equivalent to using observation indices for the trend.</blue></p>
</div>
<div style="height: 0.5em;">

</div>
<p>We start from the trend model with observation <em>indices</em> (<span class="math inline">\(t\)</span>): <span class="math display">\[\begin{align}
Y_{t}&amp;=\mathbb{E}(Y_{t})+Z_{t}\\
\textsf{where}\quad \mathbb{E}(Y_{t})&amp;=\beta_{0}+\textcolor{purple}{\beta_{1}}t &amp; &amp;\textsf{(Trend model with observation indices)}\\
\mathbb{E}(Y_{t})&amp;=\beta^{*}_{0}+\textcolor{teal}{\beta^{*}_{1}}\text{Time}_{t} &amp; &amp;\textsf{(Trend model with observation dates)}
\end{align}\]</span></p>
<p><blue><strong>Question:</strong> </blue>How are <span class="math inline">\(\textcolor{purple}{\beta_{1}}\)</span> and <span class="math inline">\(\textcolor{teal}{\beta^{*}_{1}}\)</span> related? <span class="fragment"><green><span class="math inline">\(\to\)</span> Intuitively, with quarterly data <span class="math inline">\(\beta_{1}=0.25\beta^{*}_{1}\)</span>.</green></span></p>
<ul>
<li class="fragment">We start with <span class="math inline">\(\textcolor{teal}{\text{Time}_{t}=1945.75+0.25t}\)</span>.</li>
<li class="fragment">Then plugging this into the trend model with observation dates: <span class="math display">\[\begin{align}
Y_{t}&amp;=\beta_{0}^*+\beta_{1}^{*}\textcolor{teal}{\text{Time}_{t}}+Z_{t}\\
&amp;=\beta_{0}^*+\beta_{1}^{*}(\textcolor{teal}{1945.75+0.25t})+Z_{t}\\
&amp;=\textcolor{purple}{(\beta_{0}^{*}+1945.75\beta_{1}^*)}+\textcolor{purple}{0.25\beta_{1}^{*}}t+Z_{t}
\end{align}\]</span></li>
<li class="fragment">Reading off the coefficients, we know <purple><span class="math inline">\(\beta_{0}=\beta_{0}^{*}+1045.75\beta_{1}^{*}\)</span></purple> and <purple><span class="math inline">\(\beta_{1}=0.25\beta_{1}^*\)</span></purple>.</li>
</ul>
</section>
<section id="exercise-1d-5" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Exercise 1(d)</h2>
<div class="callout-question">
<p>In previous applications we have modeled the linear trend using the observation <em>dates</em> <span class="math inline">\(\text{Time}_{t}\)</span>. Set up the same ARIMA<span class="math inline">\((p,d,q)\)</span> model for <span class="math inline">\(Y_{t}\)</span> as (c), but use the observation dates instead.</p>
<p><blue>Show how this is equivalent to using observation indices for the trend.</blue></p>
</div>
<div style="height: 0.5em;">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a></a>t <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(Y)</span>
<span id="cb40-2"><a></a>eq_b <span class="ot">&lt;-</span> <span class="fu">Arima</span>(Y, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">3</span>), <span class="at">include.drift =</span> <span class="cn">TRUE</span>) </span>
<span id="cb40-3"><a></a><span class="co"># Equivalently eq_b_xreg &lt;- Arima(Y, order = c(1,1,3), xreg = t)  </span></span>
<span id="cb40-4"><a></a><span class="fu">print</span>(<span class="fu">round</span>(eq_b<span class="sc">$</span>coef,<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    ar1     ma1     ma2     ma3   drift 
 0.8316 -0.6377  0.2380  0.1276  0.0120 </code></pre>
</div>
</div>
<div style="position: absolute; left: 39%; top: 42%; width: 110px; height: 70px; border: 3px solid purple; background: transparent; box-sizing: border-box;">

</div>
<div style="position: absolute; left: 48.5%; top: 42%; width: 110px; height: 70px; border: 0px solid teal; background: transparent; box-sizing: border-box;">
<p><purple><span class="math inline">\(\hat{\beta}_{1}\)</span></purple></p>
</div>
<div class="fragment">
<div style="height: 0.5em;">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a></a>Time <span class="ot">&lt;-</span> <span class="fu">time</span>(Y)</span>
<span id="cb42-2"><a></a><span class="co"># include.drift = FALSE is actually the default, but it is included here to </span></span>
<span id="cb42-3"><a></a><span class="co"># emphasise the point</span></span>
<span id="cb42-4"><a></a>eq_c <span class="ot">&lt;-</span> <span class="fu">Arima</span>(Y, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">3</span>), <span class="at">xreg =</span> Time, <span class="at">include.drift =</span> <span class="cn">FALSE</span>)</span>
<span id="cb42-5"><a></a><span class="fu">print</span>(<span class="fu">round</span>(eq_c<span class="sc">$</span>coef,<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    ar1     ma1     ma2     ma3    xreg 
 0.8317 -0.6377  0.2379  0.1275  0.0478 </code></pre>
</div>
</div>
<div style="position: absolute; left: 39%; top: 71%; width: 110px; height: 70px; border: 3px solid teal; background: transparent; box-sizing: border-box;">

</div>
<div style="position: absolute; left: 48.5%; top: 71%; width: 110px; height: 70px; border: 0px solid teal; background: transparent; box-sizing: border-box;">
<p><teal><span class="math inline">\(\hat{\beta_{1}^*}\)</span></teal></p>
</div>
</div>
<div class="fragment">
<div style="height: 0.5em;">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a></a><span class="fu">print</span>(eq_c<span class="sc">$</span>coef[<span class="st">"xreg"</span>]<span class="sc">/</span>eq_b<span class="sc">$</span>coef[<span class="st">"drift"</span>])   <span class="co"># beta1*/beta1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    xreg 
4.001716 </code></pre>
</div>
</div>
<div style="position: absolute; left: 15%; top: 86%; width: 110px; height: 70px; border: 0px solid teal; background: transparent; box-sizing: border-box;">
<p><span class="math inline">\(\textcolor{teal}{\hat{\beta_{1}^*}}/\textcolor{purple}{\hat{\beta_{1}}}\)</span></p>
</div>
</div>
<div class="fragment">
<p><blue>We may model the linear trend in terms of observation date or observation index, according to which is more convenient, and the resulting model will be equivalent either way.</blue></p>
</div>
</section>
<section id="exercise-1e" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Exercise 1(e)</h2>
<div class="callout-question">
<p>Use the chosen model to calculate a forecast of <blue>inflation</blue>, <span class="math inline">\(\log(CPI_{t})\)</span> and the <span class="math inline">\(CPI_{t}\)</span> itself for the March quarter of 2020.</p>
</div>
<div style="height: 0.5em;">

</div>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Note that we have selected ARMA(1,3) for <span class="math inline">\(\Delta Y_{t}\equiv \Delta\log(CPI_{t})\)</span> in Exercise 1(c).</p>
</div>
</div>
</div>
<div style="height: 0.5em;">

</div>
<div class="fragment">
<p>Forecast 2020Q1 inflation: <span class="math inline">\(\Delta{}Y_{2020Q1}=\log(CPI_{2020Q1})-\log(CPI_{2019Q4})\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy" data-id="quarto-animate-code"><code class="sourceCode r hljs"><span id="cb46-1" class="hljs-ln-code"><a></a><span class="co"># Recall: eq_a &lt;- Arima(DY, order = c(1,0,3))</span></span>
<span id="cb46-2" class="hljs-ln-code"><a></a>ForecastInflation_2020q1 <span class="ot">&lt;-</span> <span class="fu">forecast</span>(eq_a, <span class="at">h=</span><span class="dv">1</span>)<span class="sc">$</span>mean</span>
<span id="cb46-3" class="hljs-ln-code"><a></a><span class="fu">print</span>(<span class="fu">round</span>(ForecastInflation_2020q1, <span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Qtr1
2020 0.0071</code></pre>
</div>
</div>
</div>
<div class="fragment">
<div class="horizontal-line">

</div>
<p><strong>The inflation forecast is based on an approximation…</strong></p>
<p>Recall from Week 1 tutorial that for small <span class="math inline">\(r\)</span> values, <span class="math inline">\(\log(1+r)\approx r\)</span>: <span class="math display">\[\begin{align}
CPI_{2019Q4}(1+\text{inflation}_{2020Q1})&amp;=CPI_{2020Q1}\\
\log(1+\text{inflation}_{2020Q1})&amp;=\log(CPI_{2020Q1})-\log(CPI_{2019Q4})\\
\implies\qquad \color{blue}{\text{inflation}_{2020Q1}}&amp;\approx\log(CPI_{2020Q1})-\log(CPI_{2019Q4})
\end{align}\]</span></p>
</div>
</section>
<section id="exercise-1e-1" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Exercise 1(e)</h2>
<div class="callout-question">
<p>Use the chosen model to calculate a forecast of inflation, <blue><span class="math inline">\(\log(CPI_{t})\)</span></blue> and the <span class="math inline">\(CPI_{t}\)</span> itself for the March quarter of 2020.</p>
</div>
<div style="height: 0.5em;">

</div>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Note that we have selected ARMA(1,3) for <span class="math inline">\(\Delta Y_{t}\equiv \Delta\log(CPI_{t})\)</span> in Exercise 1(c).</p>
</div>
</div>
</div>
<div style="height: 0.5em;">

</div>
<p>Forecast 2020Q1 inflation: <span class="math inline">\(\Delta{}Y_{2020Q1}=\log(CPI_{2020Q1})-\log(CPI_{2019Q4})\)</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       Qtr1
2020 0.0071</code></pre>
</div>
</div>
<div style="position: absolute; left: 20%; top: 40%; width: 110px; height: 70px; border: 0px solid teal; background: transparent; box-sizing: border-box;">
<p><purple><span class="math inline">\(\widehat{\mathbb{E}}(\Delta Y_{n+1}\mid\mathscr{Y}_{n})\)</span></purple></p>
</div>
<div class="horizontal-line">

</div>
<p>Forecast 2020Q1 <span class="math inline">\(\log(CPI_{2020Q1})\equiv Y_{2020Q1}\)</span>:</p>
<ul>
<li class="fragment">First we know that <span class="math inline">\(\Delta Y_{2020Q1}=Y_{2020Q1}-Y_{2019Q4}\)</span>.</li>
<li class="fragment">On both sides take the conditional expectation based on data up to and including 2019Q4 (<span class="math inline">\(\mathscr{Y}_{2019Q4}\)</span>): <span class="math display">\[\mathbb{E}(\Delta Y_{2020Q1}\mid\mathscr{Y}_{2019Q4})=\mathbb{E}(Y_{2020Q1}\mid\mathscr{Y}_{2019Q4})-\mathbb{E}(Y_{2019Q4}\mid\mathscr{Y}_{2019Q4})\]</span></li>
<li class="fragment">Since <span class="math inline">\(Y_{2019Q4}\in\mathscr{Y}_{2019Q4}\)</span>, <span class="math inline">\(\mathbb{E}(Y_{2019Q4}\mid\mathscr{Y}_{2019Q4})=Y_{2019Q4}\)</span>, thus adding hats gives: <span class="math display">\[\widehat{\mathbb{E}}(Y_{2020Q1}\mid\mathscr{Y}_{2019Q4})=Y_{2019Q4}+\textcolor{purple}{\widehat{\mathbb{E}}(\Delta Y_{n+1}\mid\mathscr{Y}_{n})}\]</span></li>
</ul>
</section>
<section id="exercise-1e-2" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Exercise 1(e)</h2>
<div class="callout-question">
<p>Use the chosen model to calculate a forecast of inflation, <blue><span class="math inline">\(\log(CPI_{t})\)</span></blue> and the <span class="math inline">\(CPI_{t}\)</span> itself for the March quarter of 2020.</p>
</div>
<div style="height: 0.5em;">

</div>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Note that we have selected ARMA(1,3) for <span class="math inline">\(\Delta Y_{t}\equiv \Delta\log(CPI_{t})\)</span> in Exercise 1(c).</p>
</div>
</div>
</div>
<div style="height: 0.5em;">

</div>
<p>Forecast 2020Q1 inflation: <span class="math inline">\(\Delta{}Y_{2020Q1}=\log(CPI_{2020Q1})-\log(CPI_{2019Q4})\)</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       Qtr1
2020 0.0071</code></pre>
</div>
</div>
<div style="position: absolute; left: 20%; top: 40%; width: 110px; height: 70px; border: 0px solid teal; background: transparent; box-sizing: border-box;">
<p><purple><span class="math inline">\(\widehat{\mathbb{E}}(\Delta Y_{n+1}\mid\mathscr{Y}_{n})\)</span></purple></p>
</div>
<div class="horizontal-line">

</div>
<p>Forecast 2020Q1 <span class="math inline">\(\log(CPI_{2020Q1})\equiv Y_{2020Q1}\)</span>: <span class="math display">\[\widehat{\mathbb{E}}(Y_{2020Q1}\mid\mathscr{Y}_{2019Q4})=Y_{2019Q4}+\textcolor{purple}{\widehat{\mathbb{E}}(\Delta Y_{n+1}\mid\mathscr{Y}_{n})}\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy" data-id="quarto-animate-code"><code class="sourceCode r hljs"><span id="cb50-1" class="hljs-ln-code"><a></a>Forecast_logCPI_2020q1 <span class="ot">&lt;-</span> ForecastInflation_2020q1 <span class="sc">+</span> Y[<span class="fu">length</span>(Y)]</span>
<span id="cb50-2" class="hljs-ln-code"><a></a><span class="fu">print</span>(<span class="fu">round</span>(Forecast_logCPI_2020q1,<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Qtr1
2020 4.7624</code></pre>
</div>
</div>
</section>
<section id="exercise-1e-3" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Exercise 1(e)</h2>
<div class="callout-question">
<p>Use the chosen model to calculate a forecast of inflation, <blue><span class="math inline">\(\log(CPI_{t})\)</span></blue> and the <span class="math inline">\(CPI_{t}\)</span> itself for the March quarter of 2020.</p>
</div>
<div style="height: 0.5em;">

</div>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Note that we have selected ARMA(1,3) for <span class="math inline">\(\Delta Y_{t}\equiv \Delta\log(CPI_{t})\)</span> in Exercise 1(c).</p>
</div>
</div>
</div>
<div style="height: 0.5em;">

</div>
Forecast 2020Q1 <span class="math inline">\(\log(CPI_{2020Q1})\equiv Y_{2020Q1}\)</span>:
<div style="height: 0.5em;">

</div>
<div class="panel-tabset">
<ul id="tabset-3" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-3-1"><code>eq_a</code></a></li><li><a href="#tabset-3-2">Alternative - <code>eq_b</code></a></li><li><a href="#tabset-3-3">Alternative - <code>eq_c</code></a></li></ul>
<div class="tab-content">
<div id="tabset-3-1">
<p>First forecast <span class="math inline">\(\widehat{\mathbb{E}}(\Delta Y_{2020Q1}\mid\mathscr{Y}_{2019Q4})\)</span>, then obtain <span class="math inline">\(\widehat{\mathbb{E}}(\log(CPI_{2020Q1})\mid\mathscr{Y}_{2019Q4})\)</span> using the following relationship: <span class="math display">\[\widehat{\mathbb{E}}(Y_{2020Q1}\mid\mathscr{Y}_{2019Q4})=Y_{2019Q4}+\widehat{\mathbb{E}}(\Delta Y_{n+1}\mid\mathscr{Y}_{n})\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a></a><span class="co"># Recall: eq_a &lt;- Arima(DY, order = c(1,0,3))</span></span>
<span id="cb52-2"><a></a>ForecastInflation_2020q1 <span class="ot">&lt;-</span> <span class="fu">forecast</span>(eq_a, <span class="at">h=</span><span class="dv">1</span>)<span class="sc">$</span>mean</span>
<span id="cb52-3"><a></a>Forecast_logCPI_2020q1 <span class="ot">&lt;-</span> ForecastInflation_2020q1 <span class="sc">+</span> Y[<span class="fu">length</span>(Y)]</span>
<span id="cb52-4"><a></a><span class="fu">print</span>(<span class="fu">round</span>(Forecast_logCPI_2020q1,<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Qtr1
2020 4.7624</code></pre>
</div>
</div>
</div>
<div id="tabset-3-2">
<p>As an alternative, we could directly forecast <code>Y</code> with <code>eq_b</code> as previously defined:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a></a><span class="co"># Recall: eq_b &lt;- Arima(Y, order = c(1, 1, 3), include.drift = TRUE)</span></span>
<span id="cb54-2"><a></a>Forecast_logCPI_2020q1 <span class="ot">&lt;-</span> <span class="fu">forecast</span>(eq_b, <span class="at">h=</span><span class="dv">1</span>)<span class="sc">$</span>mean</span>
<span id="cb54-3"><a></a><span class="fu">print</span>(<span class="fu">round</span>(Forecast_logCPI_2020q1,<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Qtr1
2020 4.7624</code></pre>
</div>
</div>
<div style="height: 0.5em;">

</div>
<p><blue>This is useful if we were only concerned with forecasting <span class="math inline">\(Y_{2020Q1}\equiv\log(CPI_{2020Q1})\)</span> but not the inflation rate <span class="math inline">\(\Delta Y_{2020Q1}\equiv \Delta\log(CPI_{2020Q1})\)</span>.</blue></p>
</div>
<div id="tabset-3-3">
<div style="height: 0.5em;">

</div>
The same forecast for <span class="math inline">\(\log(CPI_{2020Q1})\)</span> can also be computed using <code>eq_c</code> as previously defined, where observation dates <span class="math inline">\(\text{Time}_{t}\)</span> is used for the linear trend.
<div style="height: 0.5em;">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a></a><span class="co"># It is NECESSARY to specify the value for the trend variable </span></span>
<span id="cb56-2"><a></a><span class="co"># (xreg = 2020.00) that applied for the one-step-ahead forecast:</span></span>
<span id="cb56-3"><a></a>Forecast_logCPI_2020q1_c <span class="ot">&lt;-</span> <span class="fu">forecast</span>(eq_c, <span class="at">xreg =</span> <span class="fl">2020.00</span>)<span class="sc">$</span>mean</span>
<span id="cb56-4"><a></a><span class="fu">print</span>(<span class="fu">round</span>(Forecast_logCPI_2020q1_c, <span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Qtr1
2020 4.7624</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="exercise-1e-4" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Exercise 1(e)</h2>
<div class="callout-question">
<p>Use the chosen model to calculate a forecast of inflation, <span class="math inline">\(\log(CPI_{t})\)</span> and the <blue><span class="math inline">\(CPI_{t}\)</span> itself</blue> for the March quarter of 2020.</p>
</div>
<div style="height: 0.5em;">

</div>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Note that we have selected ARMA(1,3) for <span class="math inline">\(\Delta Y_{t}\equiv \Delta\log(CPI_{t})\)</span> in Exercise 1(c).</p>
</div>
</div>
</div>
<div style="height: 0.1em;">

</div>
<p><strong>How can we forecast the 2020Q1 CPI?</strong></p>
<p>We know that <span class="math display">\[\begin{align}
\color{blue}{\text{inflation}_{2020Q1}}&amp;\approx\log(CPI_{2020Q1})-\log(CPI_{2019Q4})
\end{align}\]</span></p>
<div class="fragment">
<p>thus we have <span class="math inline">\(\widehat{CPI}_{2020Q1}=CPI_{2019Q4}\times(1+\widehat{\operatorname{inflation}}_{2020Q1})\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode numberSource r number-lines code-with-copy" data-id="quarto-animate-code"><code class="sourceCode r hljs"><span id="cb58-1" class="hljs-ln-code"><a></a><span class="co"># Create a ts of CPI (i.e. not log CPI)</span></span>
<span id="cb58-2" class="hljs-ln-code"><a></a>CPI <span class="ot">&lt;-</span> <span class="fu">ts</span>(dt<span class="sc">$</span>CPI, <span class="at">start=</span><span class="fu">c</span>(<span class="dv">1922</span>,<span class="dv">2</span>), <span class="at">end=</span><span class="fu">c</span>(<span class="dv">2025</span>,<span class="dv">2</span>), <span class="at">frequency=</span><span class="dv">4</span>)</span>
<span id="cb58-3" class="hljs-ln-code"><a></a>CPI_2019q4 <span class="ot">&lt;-</span> CPI[<span class="fu">which</span>(<span class="fu">time</span>(CPI)<span class="sc">==</span><span class="fl">2019.75</span>)]</span>
<span id="cb58-4" class="hljs-ln-code"><a></a></span>
<span id="cb58-5" class="hljs-ln-code"><a></a><span class="co"># Forecast CPI for 2020q1</span></span>
<span id="cb58-6" class="hljs-ln-code"><a></a>ForecastCPI_2020q1_a <span class="ot">&lt;-</span> CPI_2019q4<span class="sc">*</span>(<span class="dv">1</span><span class="sc">+</span>ForecastInflation_2020q1)</span>
<span id="cb58-7" class="hljs-ln-code"><a></a><span class="fu">print</span>(ForecastCPI_2020q1_a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Qtr1
2020 117.0254</code></pre>
</div>
</div>
</div>
</section>
<section id="exercise-1e-5" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Exercise 1(e)</h2>
<div class="callout-question">
<p>Use the chosen model to calculate a forecast of inflation, <span class="math inline">\(\log(CPI_{t})\)</span> and the <blue><span class="math inline">\(CPI_{t}\)</span> itself</blue> for the March quarter of 2020.</p>
</div>
<div style="height: 0.5em;">

</div>
<p><strong>How can we forecast the 2020Q1 CPI?</strong></p>
<p>First approach: <span class="math inline">\(\widehat{CPI}_{2020Q1}=CPI_{2019Q4}\times(1+\widehat{\operatorname{inflation}}_{2020Q1})\)</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>         Qtr1
2020 117.0254</code></pre>
</div>
</div>
<div class="horizontal-line">

</div>
<div class="fragment">
<blue>Second approach: take the exponential to “reverse” the log transformation <span class="math display">\[\widehat{CPI_{2020Q1}}=\exp(\widehat{\log(CPI_{2020Q1}})\]</span></blue>
<div style="height: 0.3em;">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode numberSource r number-lines code-with-copy" data-id="quarto-animate-code"><code class="sourceCode r hljs"><span id="cb61-1" class="hljs-ln-code"><a></a>ForecastCPI_2020q1_b <span class="ot">&lt;-</span> <span class="fu">exp</span>(Forecast_logCPI_2020q1)</span>
<span id="cb61-2" class="hljs-ln-code"><a></a><span class="fu">print</span>(ForecastCPI_2020q1_b)    <span class="co"># Forecasted CPI level at 2020Q1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Qtr1
2020 117.0284</code></pre>
</div>
</div>
</div>
</section>
<section id="exercise-1e-6" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Exercise 1(e)</h2>
<div class="callout-question">
<p>Use the chosen model to calculate a forecast of inflation, <span class="math inline">\(\log(CPI_{t})\)</span> and the <blue><span class="math inline">\(CPI_{t}\)</span> itself</blue> for the March quarter of 2020.</p>
</div>
<div style="height: 0.5em;">

</div>
<p><strong>Remarks on the CPI forecasts:</strong></p>
<p>Both approaches are approximations.</p>
<div class="fragment">
<div class="horizontal-line">

</div>
<p>First approach: <span class="math inline">\(\widehat{CPI}_{2020Q1}=CPI_{2019Q4}\times (1+\color{purple}{\underbrace{\widehat{\text{inflation}}_{2020Q1}}_{\text{approximation}}})\)</span></p>
</div>
<div class="fragment">
<div class="horizontal-line">

</div>
<p>Second approach: <span class="math inline">\(\widehat{CPI}_{2020Q1}=\exp(\log(\widehat{CPI}_{2020Q1}))\)</span></p>
</div>
</section>
<section id="exercise-1e-7" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Exercise 1(e)</h2>
<div class="callout-question">
<p>Use the chosen model to calculate a forecast of inflation, <span class="math inline">\(\log(CPI_{t})\)</span> and the <blue><span class="math inline">\(CPI_{t}\)</span> itself</blue> for the March quarter of 2020.</p>
</div>
<div style="height: 0.5em;">

</div>
<p><strong>Remarks on the CPI forecasts:</strong></p>
<p>Both approaches are approximations.</p>
<div class="horizontal-line">

</div>
<p>First approach: <span class="math inline">\(\widehat{CPI}_{2020Q1}=CPI_{2019Q4}\times (1+\color{purple}{\underbrace{\widehat{\text{inflation}}_{2020Q1}}_{\text{approximation}}})\)</span></p>
<div class="horizontal-line">

</div>
Second approach: <span class="math inline">\(\widehat{CPI}_{2020Q1}=\exp(\color{blue}{\hat{\mathbb{E}}[\log(CPI_{2020Q1})\mid\mathscr{Y}_{2019Q4}]}\color{black}{)}\)</span>
<div style="height: 0.5em;">

</div>
<p><oblue> <strong>Question:</strong> Does the following hold? <span class="math display">\[\color{blue}{\mathbb{E}[{CPI}_{2020Q1}\mid\mathscr{Y}_{2019Q4}]\overset{?}{=}\exp(\mathbb{E}[\log(CPI_{2020Q1})\mid \mathscr{Y}_{2019Q4}])}\]</span> </oblue></p>
<div class="fragment">
<p><blue> <strong>Answer:</strong> No.&nbsp;This is because of Jensen’s inequality - since <span class="math inline">\(\exp(x)\)</span> is convex: <span class="math display">\[\mathbb{E}[\exp(\log(CPI_{2020Q1})\mid \mathscr{Y}_{2019Q4})]&gt;\exp(\mathbb{E}[\log(CPI_{2020Q1})\mid \mathscr{Y}_{2019Q4}])\]</span> </blue></p>
</div>
</section>
<section id="exercise-1e-8" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Exercise 1(e)</h2>
<div class="callout-question">
<p>Use the chosen model to calculate a forecast of inflation, <span class="math inline">\(\log(CPI_{t})\)</span> and the <blue><span class="math inline">\(CPI_{t}\)</span> itself</blue> for the March quarter of 2020.</p>
</div>
<div style="height: 0.5em;">

</div>
<p><strong>Remarks on the CPI forecasts:</strong></p>
<p>Both approaches are approximations.</p>
<div class="horizontal-line">

</div>
<p>First approach: <span class="math inline">\(\widehat{CPI}_{2020Q1}=CPI_{2019Q4}\times (1+\color{purple}{\underbrace{\widehat{\text{inflation}}_{2020Q1}}_{\text{approximation}}})\)</span></p>
<div class="horizontal-line">

</div>
Second approach: <span class="math inline">\(\widehat{CPI}_{2020Q1}=\exp(\hat{\mathbb{E}}[\log(CPI_{2020Q1})\mid\mathscr{Y}_{2019Q4}]\color{black}{)}\)</span>
<div style="height: 0.5em;">

</div>
<p><blue> Thus this estimator is actually biased for the conditional mean <span class="math inline">\(\mathbb{E}[CPI_{2020Q1}\mid\mathscr{Y}_{2019Q4}]\)</span>: <span class="math display">\[\mathbb{E}[CPI_{2020Q1}\mid\mathscr{Y}_{2019Q4}]&gt;\exp(\mathbb{E}[\log(CPI_{2020Q1})\mid \mathscr{Y}_{2019Q4}])\]</span> </blue></p>
<div class="fragment">
<p><green> Nevertheless, in practice and <a href="https://www.sciencedirect.com/science/article/abs/pii/S0169207011000112">by research</a>, simply taking the exponential tends to work well in providing a good approximation. So we will continue to take exponentials whenever required. </green></p>
</div>
</section>
<section id="exercise-2" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Exercise 2</h2>
<p>Consider a time series model consisting of a trend equation and AR(p) equation: <span class="math display">\[\begin{align}
Y_{t}&amp;=X_{t}^{\top}\beta +Z_{t}\\
Z_{t}&amp;=\phi_{1}Z_{t-1}+\cdots+\phi_{p}Z_{t-p}+U_{t}
\end{align}\]</span></p>
<div class="fragment">
<p><purple> The ADF equation for this model is: <span class="math display">\[\Delta Y_{t}=\varphi Y_{t-1}+X_{t}^{\top}\beta^{*}+\sum^{p-1}_{k=1}\psi_{k}\Delta Y_{t-k}+U_{t}\]</span> </purple> i.e.&nbsp;a regression of <span class="math inline">\(\Delta Y_{t}\)</span> on</p>
<ul>
<li><span class="math inline">\(Y_{t-1}\)</span>: variable of interest for the ADF test;</li>
<li><span class="math inline">\(X_{t}\)</span>: same set of deterministic variables as specified in the original model</li>
<li>lags <span class="math inline">\(1,\dots,p-1\)</span> of <span class="math inline">\(\Delta Y_{t}\)</span> (i.e.&nbsp;one fewer lag than in the original model).</li>
</ul>
<p>Note the coefficients on <span class="math inline">\(X_{t}\)</span> in the original model (<span class="math inline">\(\beta\)</span>) differ from those in the ADF test equation (<span class="math inline">\(\beta^*\)</span>).</p>
</div>
</section>
<section id="exercise-2-1" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Exercise 2</h2>
<p>Consider a time series model consisting of a trend equation and AR(p) equation: <span class="math display">\[\begin{align}
Y_{t}&amp;=X_{t}^{\top}\beta +Z_{t}\\
Z_{t}&amp;=\phi_{1}Z_{t-1}+\cdots+\phi_{p}Z_{t-p}+U_{t}
\end{align}\]</span></p>
<p><purple> The ADF equation for this model is: <span class="math display">\[\Delta Y_{t}=\varphi Y_{t-1}+X_{t}^{\top}\beta^{*}+\sum^{p-1}_{k=1}\psi_{k}\Delta Y_{t-k}+U_{t}\]</span> </purple></p>
Note the coefficients on <span class="math inline">\(X_{t}\)</span> in the original model (<span class="math inline">\(\beta\)</span>) differ from those in the ADF test equation (<span class="math inline">\(\beta^*\)</span>). <span class="fragment"><teal><span class="math inline">\(\to\)</span> How are these coefficients related?</teal></span>
<div style="height: 1em;">

</div>
<div class="fragment">
<div class="callout-question">
<p>Let’s work through an example of how a specific time series model can be rearranged into the ADF equation. Consider a model with intercept and linear trend, and 2 lags in the AR equation: <span class="math display">\[\begin{align}
Y_{t}&amp;=\beta_{0}+\beta_{1} t+Z_{t}\\
Z_{t}&amp;=\phi_{1}Z_{t-1}+\phi_{2}Z_{t-2}+U_{t}
\end{align}\]</span> <blue> Goal: Rewrite these equations in the form of the ADF equation, derive <span class="math inline">\(\beta_{0}^{*}\)</span> and <span class="math inline">\(\beta_{1}^{*}\)</span>: <span class="math display">\[\Delta Y_{t}=\varphi Y_{t-1}+\beta_{0}^{*}+\beta_{1}^{*}t+\psi_{1}\Delta Y_{t-1}+U_{t}\]</span> </blue></p>
</div>
</div>
</section>
<section id="exercise-2-2" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Exercise 2</h2>
<div class="callout-question">
<p>Consider a model with intercept and linear trend, and 2 lags in the AR equation: <span class="math display">\[\begin{align}
Y_{t}&amp;=\beta_{0}+\beta_{1} t+Z_{t}\\
Z_{t}&amp;=\phi_{1}Z_{t-1}+\phi_{2}Z_{t-2}+U_{t}
\end{align}\]</span> <blue> Goal: Rewrite these equations in the form of the ADF equation, derive <span class="math inline">\(\beta_{0}^{*}\)</span> and <span class="math inline">\(\beta_{1}^{*}\)</span>: <span class="math display">\[\Delta Y_{t}=\varphi Y_{t-1}+\beta_{0}^{*}+\beta_{1}^{*}t+\psi_{1}\Delta Y_{t-1}+U_{t}\]</span> </blue></p>
</div>
<div style="height: 0.5em;">

</div>
<div class="panel-tabset">
<ul id="tabset-4" class="panel-tabset-tabby"><li><a data-tabby-default="" href="#tabset-4-1">Step 1</a></li><li><a href="#tabset-4-2">Step 2</a></li><li><a href="#tabset-4-3">Step 2 Derivations</a></li><li><a href="#tabset-4-4">Step 3</a></li><li><a href="#tabset-4-5">Step 3 Algebra</a></li><li><a href="#tabset-4-6">Discussion</a></li></ul>
<div class="tab-content">
<div id="tabset-4-1">
Re-express the autoregressive equation in the form <span class="math display">\[\Delta Z_{t}=\varphi Z_{t-1}+\psi_{1}\Delta Z_{t-1}+U_{t}\]</span> where <span class="math inline">\(\varphi = \phi_{1}+\phi_{2}-1\)</span> and <span class="math inline">\(\psi_{1}=-\phi_{2}\)</span>.
<div class="horizontal-line">

</div>
<p><span class="math display">\[\begin{align}
Z_{t}&amp;=\phi_{1}Z_{t-1}+\phi_{2}Z_{t-2}+U_{t}\\
Z_{t}&amp;=\phi_{1}Z_{t-1}\textcolor{magenta}{+\phi_{2}Z_{t-1}-\phi_{2}Z_{t-1}}+\phi_{2}Z_{t-2}+U_{t}\\
Z_{t}&amp;=\textcolor{blue}{(\phi_{1}+\phi_{2})Z_{t-1}}\textcolor{green}{-\phi_{2}\Delta Z_{t-1}}+U_{t}\\
Z_{t}\textcolor{red}{-Z_{t-1}}&amp;=\textcolor{red}{-Z_{t-1}}+(\phi_{1}+\phi_{2})Z_{t-1}-\phi_{2}\Delta Z_{t-1}+U_{t}\\
\Delta Z_{t}&amp;=\varphi Z_{t-1}+\psi_{1}\Delta Z_{t-1}+U_{t}

\end{align}\]</span> where <span class="math inline">\(\varphi=\phi_{1}+\phi_{2}-1\)</span> and <span class="math inline">\(\psi_{1}=-\phi_{2}\)</span>.</p>
</div>
<div id="tabset-4-2">
<p>From Step 1 we have <span class="math display">\[\textcolor{red}{\Delta Z_{t}}=\varphi \textcolor{blue}{Z_{t-1}}+\psi_{1}\textcolor{magenta}{\Delta Z_{t-1}}+U_{t}.\]</span> Using the trend equation <span class="math inline">\(Y_{t}=\beta_{0}+\beta_{1}t+Z_{t}\)</span>, derive the following: <span class="math display">\[\begin{align}
\textcolor{red}{\Delta Z_{t}}\;&amp;\textcolor{red}{=\Delta Y_{t}-\beta_{1}}\\
\textcolor{magenta}{\Delta Z_{t-1}}\;&amp;\textcolor{magenta}{=\Delta Y_{t-1}-\beta_{1}}\\
\textcolor{blue}{Z_{t-1}}\;&amp;\textcolor{blue}{=Y_{t-1}-\beta_{0}-\beta_{1}(t-1)}
\end{align}\]</span> substituting gives <span class="math inline">\((\textcolor{red}{\Delta Y_{t}-\beta_{1}})=\varphi(\textcolor{blue}{Y_{t-1}-\beta_{0}-\beta_{1}(t-1)})+\psi_{1}(\textcolor{magenta}{\Delta Y_{t-1}-\beta_{1}})+U_{t}\)</span></p>
</div>
<div id="tabset-4-3">
<ul>
<li>Starting from the trend equation <span class="math inline">\(Y_{t}=\beta_{0}+\beta_{1}t+Z_{t}\)</span>, the first lag is: <span class="math display">\[\begin{align}
Y_{t-1}&amp;=\beta_{0}+\beta_{1}(t-1)+Z_{t-1}\quad\quad\quad (1)\\
\implies \textcolor{blue}{Z_{t-1}}\;&amp;\textcolor{blue}{=Y_{t-1}-\beta_{0}-\beta_{1}(t-1)}
\end{align}\]</span></li>
<li>Using equation (1) and the trend equation, we thus know that: <span class="math display">\[\begin{align}
&amp;&amp;Y_{t}-Y_{t-1}&amp;=(\beta_{0}-\beta_{0})+\beta_{1}(t-(t-1))+Z_{t}-Z_{t-1}\\
&amp;&amp;\Delta Y_{t}&amp;=\beta_{1}+\Delta {Z_{t}}\\
\implies&amp;&amp; \textcolor{red}{\Delta Z_{t}}\;&amp;\textcolor{red}{=\Delta Y_{t}-\beta_{1}}\\
\implies&amp;&amp; \textcolor{magenta}{\Delta Z_{t-1}}\;&amp;\textcolor{magenta}{=\Delta Y_{t-1}-\beta_{1}}
\end{align}\]</span></li>
</ul>
</div>
<div id="tabset-4-4">
<p>From Step 2 we have: <span class="math display">\[(\textcolor{red}{\Delta Y_{t}-\beta_{1}})=\varphi(\textcolor{blue}{Y_{t-1}-\beta_{0}-\beta_{1}(t-1)})+\psi_{1}(\textcolor{magenta}{\Delta Y_{t-1}-\beta_{1}})+U_{t}\]</span> Simplify this to the form of ADF test equation: <span class="math display">\[\Delta Y_{t}=\varphi Y_{t-1}+\textcolor{green}{\beta_{0}^{*}}+\textcolor{teal}{\beta_{1}^{*}}t+\psi_{1}\Delta Y_{t-1}+U_{t}\]</span> where <span class="math inline">\(\textcolor{green}{\beta_{0}^{*}=\beta_{1}-\varphi\beta_{0}+\varphi\beta_{1}-\psi_{1}\beta_{1}}\)</span> and <span class="math inline">\(\textcolor{teal}{\beta_{1}^{*}=-\varphi\beta_{1}}\)</span>.</p>
</div>
<div id="tabset-4-5">
<p><span class="math display">\[\begin{align}
(\Delta Y_{t}-\beta_{1})&amp;=\varphi(Y_{t-1}-\beta_{0}-\beta_{1}(t-1))+\psi_{1}(\Delta Y_{t-1}-\beta_{1})+U_{t}\\
\Delta Y_{t}&amp;=\beta_{1}+\varphi Y_{t-1}-\varphi\beta_{0}-\varphi\beta_{1} t+\varphi\beta_{1}+\psi_{1}\Delta Y_{t-1}-\psi_{1}\beta_{1}+U_{t}\\
\Delta Y_{t}&amp;=\varphi Y_{t-1}+\beta_{1}-\varphi\beta_{0}+\varphi\beta_{1}-\psi_{1}\beta_{1}-\varphi\beta_{1}t+\psi_{1}\Delta Y_{t-1}+U_{t}\\
\Delta Y_{t}&amp;=\varphi Y_{t-1}+\textcolor{green}{\underbrace{(\beta_{1}-\varphi\beta_{0}+\varphi\beta_{1}-\psi_{1}\beta_{1})}_{\equiv\beta_{0}^{*}}}+\textcolor{teal}{\underbrace{(-\varphi\beta_{1})}_{\equiv\beta_{1}^{*}}}t+\psi_{1}\Delta Y_{t-1}+U_{t}\\
\Delta Y_{t}&amp;=\varphi Y_{t-1}+\textcolor{green}{\beta_{0}^{*}}+\textcolor{teal}{\beta_{1}^{*}}t+\psi_{1}\Delta Y_{t-1}+U_{t}
\end{align}\]</span> where <span class="math inline">\(\textcolor{green}{\beta_{0}^{*}=\beta_{1}-\varphi\beta_{0}+\varphi\beta_{1}-\psi_{1}\beta_{1}}\)</span> and <span class="math inline">\(\textcolor{teal}{\beta_{1}^{*}=-\varphi\beta_{1}}\)</span>.</p>
</div>
<div id="tabset-4-6">
<ul>
<li>This derivation is intended to show how the ADF test equation follows from a time series model, including:
<ul>
<li>how the lag length is reduced by one, and</li>
<li>how the deterministic coefficients differ between the trend equation and ADF test equation.</li>
</ul></li>
<li>Having seen this once, the details become practically unimportant thereafter.
<ul>
<li>The values of the deterministic coefficients in the ADF test regression are not directly interesting in themselves.</li>
</ul></li>
<li>The important thing is the specification of an appropriate ADF test equation from a time series model if it has already been specified.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="section" class="slide level2" data-background-color="#000F46">
<h2></h2>
<div style="height: 85vh; display: flex; align-items: center; justify-content: center; color: white; font-size: 2em;">
<p>Thank you for coming!</p>
</div>
<script>
document.querySelectorAll("myimage").forEach(el => {
  const src = el.getAttribute("src");
  const width = el.getAttribute("width") || "100%";

  const img = document.createElement("img");
  img.src = src;
  img.style.width = width;
  img.style.maxWidth = "100%";  // prevent overflow
  el.style.display = "block";
  el.style.textAlign = "center";
  
  el.appendChild(img);
});
</script>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Access Slides: <code>pengyunc.github.io/TSAF_Week6</code></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1300,

        height: 950,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/pengyunc\.github\.io\/TSAF_Week6\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>